Repository JuliaParallel/MPI.jl, pull requests merged in 2022-09, with the labels that each got.

#625 Fix indentation of `Comm_remote_group` docstring
  src/comm.jl
Labels: documentation

#629 Add `TOML` to test dependencies
  test/Project.toml
Labels: CI

#630 Wrap `MPI_Get_processor_name` function
  docs/src/reference/environment.md
  src/environment.jl
  test/test_test.jl
Labels: enhancement

#648 add _format key to MPIPreferences
  docs/src/configuration.md
  docs/src/reference/mpipreferences.md
  lib/MPIPreferences/src/MPIPreferences.jl
Labels: MPIPreferences

#633 Remove outdated references to {send,recv}{type,count} in `Sendrecv!` docstring
  src/pointtopoint.jl
Labels: documentation

#653 [CI] Cancel old jobs if there are new commits on same branch
  .github/workflows/Documenter.yml
  .github/workflows/ShellCheck.yml
  .github/workflows/UnitTests.yml
Labels: CI

#654 [docs] Elaborate on the difference between high- and low-level API
  docs/src/reference/api.md
  docs/src/usage.md
Labels: documentation, API

#635 add `create_hvector` (support `MPI_Type_create_hvector`)
  docs/src/reference/advanced.md
  src/datatypes.jl
  test/test_datatype.jl
Labels: enhancement
