Repository JuliaParallel/MPI.jl, pull requests merged in 2022-10, with the labels that each got.

#657 [docs] Minor fixes to configuration instructions
  docs/src/configuration.md
  docs/src/knownissues.md
Labels: documentation

#656 Improve low-level `API` documentation
  docs/src/reference/api.md
  gen/src/MPIgenerator.jl
  gen/src/generator.toml
  src/api/api.jl
  src/api/generated_api.jl
Labels: documentation, API

#659 [CI] Limit running invalidations to PRs which touch source code
  .github/workflows/Invalidations.yml
Labels: CI

#660 Better detection of Intel oneAPI MPI version number
  .github/workflows/UnitTests.yml
  lib/MPIPreferences/src/MPIPreferences.jl
Labels: CI, Intel MPI

#662 Transition guide from v0.19 and earlier to v0.20+
  docs/src/configuration.md
  lib/MPIPreferences/src/MPIPreferences.jl
Labels: documentation

#647 Update buildkite to use latest Julia version
  .buildkite/pipeline.yml
  test/common.jl
Labels: CI

#672 AMDGPU does not work on Julia 1.8, so test on nightly
  .buildkite/pipeline.yml
Labels: rocm

#673 add support for persistent requests
  Project.toml
  docs/src/reference/pointtopoint.md
  src/pointtopoint.jl
  test/test_persistent.jl
Labels: enhancement
