Repository JuliaParallel/MPI.jl, pull requests merged in 2023-11, with the labels that each got.

#788 [CI] Use Spack OCI build cache for MPI packages
  .ci/mvapich/spack.yaml
  .github/workflows/UnitTests.yml
Labels: CI

#790 [CI] Oversubscribe in OpenMPI jobs
  .github/workflows/UnitTests.yml
Labels: CI

#785 deal with vendor=cray but no gtl
  lib/MPIPreferences/Project.toml
  lib/MPIPreferences/src/MPIPreferences.jl
  lib/MPIPreferences/src/parse_cray_cc.jl
Labels: Cray MPI

#791 Skip threads tests which are known to fail
  test/runtests.jl
Labels: CI, Windows, Intel MPI
