Repository JuliaParallel/MPI.jl, pull requests merged in 2023-01, with the labels that each got.

#626 document how to pass MPI.Comm objects to C
  docs/src/reference/comm.md
Labels: documentation

#700 test on mvapich
  .ci/mvapich/spack.yaml
  .github/workflows/UnitTests.yml
  test/runtests.jl
Labels: CI, MVAPICH2 MPI

#704 [CI] Use newer versions of some GitHub actions
  .github/workflows/Documenter.yml
  .github/workflows/PreviewCleanup.yml
  .github/workflows/ShellCheck.yml
  .github/workflows/UnitTests.yml
Labels: CI

#703 Update docs/examples/09-graph_communication.jl
  docs/examples/09-graph_communication.jl
Labels: documentation
