Repository JuliaParallel/MPI.jl, pull requests merged in 2024-02, with the labels that each got.

#814 [CI] Use containers with `jq` preinstalled
  .github/workflows/UnitTests.yml
Labels: CI

#818 [CI] Use oneAPI MPI 2021.11.0
  .github/workflows/UnitTests.yml
Labels: CI, Intel MPI

#819 [CI] Run tests on Apple Silicon
  .github/workflows/UnitTests.yml
Labels: macOS, CI, aarch64

#813 known issues: further clarification regarding UCX_ERROR_SIGNALS
  docs/src/knownissues.md
Labels: documentation
