Repository JuliaParallel/MPI.jl, pull requests merged in 2024-06, with the labels that each got.

#836 [CI] Update MPIWrapper to v2.11.0
  .github/workflows/UnitTests.yml
Labels: CI

#840 CUDA CI no longer has version tag
  .buildkite/pipeline.yml
  src/environment.jl
  test/runtests.jl
Labels: CUDA :flower_playing_cards:, CI

#844 Fix ROCm CI
  .buildkite/pipeline.yml
  Project.toml
  test/Project.toml
Labels: CI, rocm

#821 Add `has_rocm` for OpenMPI
  docs/src/knownissues.md
  docs/src/reference/library.md
  docs/src/usage.md
  src/environment.jl
  test/test_basic.jl
Labels: Open MPI, rocm
