Repository JuliaParallel/MPI.jl, pull requests merged in 2024-04, with the labels that each got.

#810 Detect MVAPICH 3
  .github/workflows/UnitTests.yml
  lib/MPIPreferences/src/MPIPreferences.jl
Labels: MVAPICH MPI

#831 [CI] Set `DYLD_FALLBACK_LIBRARY_PATH` in tests with Homebrew MPI
  .github/workflows/UnitTests.yml
Labels: macOS, CI

#830 Fix typos in some docstring
  src/collective.jl
Labels: documentation
